pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "com.android.application" || requested.id.id == "com.android.library") {
                // Change the AGP version below to one compatible with your Gradle wrapper
                useModule("com.android.tools.build:gradle:8.5.0")
            }
        }
    }
}
rootProject.name = "switchlabeled"
