plugins {
    id 'com.android.library'
    id 'maven-publish'
    id 'signing'
}

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'io.github.exaland.switchlabeled'
    compileSdk 34

    defaultConfig {
        minSdk 23
        consumerProguardFiles "consumer-rules.pro"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    // Publier AAR + Sources + Javadoc
    publishing {
        singleVariant("release") {
            withSourcesJar()
            withJavadocJar()
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
}

publishing {
    publications {
        create("release", MavenPublication) {
            groupId = "io.github.exaland"
            artifactId = "switchlabeled"
            version = "1.0.0"

            pom {
                name.set("LabeledSwitch")
                description.set("A Material You labeled switch for Android")
                url.set("https://github.com/exaland/switchlabeled")
                licenses {
                    license {
                        name.set("Apache License 2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                    }
                }
                developers {
                    developer {
                        id.set("exaland")
                        name.set("Alexandre Magnier")
                    }
                }
                scm {
                    connection.set("scm:git:https://github.com/exaland/switchlabeled.git")
                    developerConnection.set("scm:git:https://github.com/exaland/switchlabeled.git")
                    url.set("https://github.com/exaland/switchlabeled")
                }
            }
        }
    }
}

// GPG signing configuration (in-memory recommended for CI/CD)
signing {
    useGpgCmd()
    sign(publishing.publications["release"])
}

// Repositories for publishing (Maven Central / Sonatype OSSRH)
publishing {
    repositories {
        maven {
            name = "OSSRH"
            url = uri("https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/")
            credentials {
                username = project.findProperty("ossrhUsername") ?: System.getenv("OSSRH_USERNAME")
                password = project.findProperty("ossrhPassword") ?: System.getenv("OSSRH_PASSWORD")
            }
        }
    }
}
